[2023-12-07T17:01:21.863+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_scraping_dag.get_category_urls scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-12-07T17:01:21.872+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_scraping_dag.get_category_urls scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-12-07T17:01:21.873+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-07T17:01:21.884+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_category_urls> on 2023-09-04 00:00:00+00:00
[2023-12-07T17:01:21.892+0000] {standard_task_runner.py:57} INFO - Started process 6385 to run task
[2023-12-07T17:01:21.895+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_scraping_dag', 'get_category_urls', 'scheduled__2023-09-04T00:00:00+00:00', '--job-id', '1659', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpbonkx2sn']
[2023-12-07T17:01:21.898+0000] {standard_task_runner.py:85} INFO - Job 1659: Subtask get_category_urls
[2023-12-07T17:01:21.935+0000] {task_command.py:416} INFO - Running <TaskInstance: my_scraping_dag.get_category_urls scheduled__2023-09-04T00:00:00+00:00 [running]> on host 63b0c7e341c0
[2023-12-07T17:01:22.016+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_scraping_dag' AIRFLOW_CTX_TASK_ID='get_category_urls' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-04T00:00:00+00:00'
[2023-12-07T17:01:22.019+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 46, in get_category_urls
    soup = get_soup(base_url, headers)
  File "/opt/airflow/dags/main.py", line 41, in get_soup
    response = requests.get(url, headers=headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'
[2023-12-07T17:01:22.027+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_scraping_dag, task_id=get_category_urls, execution_date=20230904T000000, start_date=20231207T170121, end_date=20231207T170122
[2023-12-07T17:01:22.037+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1659 for task get_category_urls ('str' object has no attribute 'items'; 6385)
[2023-12-07T17:01:22.075+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-07T17:01:22.146+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-07T17:04:40.054+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_scraping_dag.get_category_urls scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-12-07T17:04:40.058+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_scraping_dag.get_category_urls scheduled__2023-09-04T00:00:00+00:00 [queued]>
[2023-12-07T17:04:40.058+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-07T17:04:40.063+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_category_urls> on 2023-09-04 00:00:00+00:00
[2023-12-07T17:04:40.065+0000] {standard_task_runner.py:57} INFO - Started process 7824 to run task
[2023-12-07T17:04:40.067+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_scraping_dag', 'get_category_urls', 'scheduled__2023-09-04T00:00:00+00:00', '--job-id', '2337', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpcfa6f4wf']
[2023-12-07T17:04:40.069+0000] {standard_task_runner.py:85} INFO - Job 2337: Subtask get_category_urls
[2023-12-07T17:04:40.091+0000] {task_command.py:416} INFO - Running <TaskInstance: my_scraping_dag.get_category_urls scheduled__2023-09-04T00:00:00+00:00 [running]> on host 63b0c7e341c0
[2023-12-07T17:04:40.135+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_scraping_dag' AIRFLOW_CTX_TASK_ID='get_category_urls' AIRFLOW_CTX_EXECUTION_DATE='2023-09-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-04T00:00:00+00:00'
[2023-12-07T17:04:40.137+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 46, in get_category_urls
    soup = get_soup(base_url, headers)
  File "/opt/airflow/dags/main.py", line 41, in get_soup
    response = requests.get(base_url, headers=headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 489, in prepare_headers
    for header in headers.items():
AttributeError: 'str' object has no attribute 'items'
[2023-12-07T17:04:40.141+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_scraping_dag, task_id=get_category_urls, execution_date=20230904T000000, start_date=20231207T170440, end_date=20231207T170440
[2023-12-07T17:04:40.146+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 2337 for task get_category_urls ('str' object has no attribute 'items'; 7824)
[2023-12-07T17:04:40.160+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-07T17:04:40.173+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
